[build]
  command = "pip install -r requirements.txt"
  publish = "."

[functions]
  directory = "netlify/functions"

[functions."*"] # Tüm fonksiyonlar için geçerli ayar
  runtime = "python3.11"